# 服务器配置
server:
  port: 50001
  name: XiaojiuServer
  unit-split-break: <<<END>>> # 请求单元分隔符号
  socket-max-wait-time: 3000 # socket最大等待输入时间（毫秒）
  access-control-allow-origin: "*" # cors跨域请求头，如果没有则不会添加

# 动态线程池配置
thread-pool:
  pool:
    max-thread: 20 # 最大线程数
    core-thread: 10 # 核心线程数
    queue-capacity: 10 # 任务队列大小
    long-connect-max-thread: 10 # 最大长连接线程数，推荐为最大线程数的一半
    # 拒绝策略，可提供的选择：THROW_EXCEPTION(抛出异常)
    # THROW_TASK(不执行该任务) THROW_QUEUE_TASK(将线程池里最早进入队列的任务抛弃)
    reject-strategy: THROW_TASK
  thread:
    thread-name: thread # 工作线程名称
    max-free-time: 180 # 普通线程池线程最大闲置时间(秒)，超时后会被线程池回收

# 可视化界面配置
monitor:
  enable: true # 是否开启可视化界面
  web-path: monitor-service # web请求根路径
  allow-ips: [] # 请求IP白名单（IPV4、IPV6均可）
  index-path: resource/monitor/index.html # 可视化界面主页主页路径（从扫描到的网络程序jar包为根目录）

# MVC配置
mvc:
  index-path: /webpage/index.html # 主页路径（从扫描到的网络程序jar包为根目录）
  resource-path: [static,webpage] # 静态资源映射路径（使用数组，从扫描到的网络程序jar包为根目录）

# IOC配置
ioc:
  ext-program-path: ext # 拓展程序jar包扫描路径
  scan-package: [program] # 拓展程序注入class扫描路径

# 日志配置
log:
  choose-class: TestLogServiceImpl # 拓展程序的类选择，如果没有找到则使用默认程序

# TCP聊天室模块
chat:
  message-cache-num: 2 # 消息缓存块数量
  cache-capacity: 500 # 消息缓存块容量
  chat-image-path: D:/Phantom/Images # 消息图片存储路径

