# 服务器配置
server:
  port: 50001

# 动态线程池配置
thread-pool:
  pool:
    max-thread: 20 # 最大线程数
    core-thread: 10 # 核心线程数
    queue-capacity: 10 # 任务队列大小
    long-connect-max-thread: 10 # 最大长连接线程数，推荐为最大线程数的一半
    # 拒绝策略，可提供的选择：THROW_EXCEPTION(抛出异常)
    # THROW_TASK(不执行该任务) THROW_QUEUE_TASK(将线程池里最早进入队列的任务)
    reject-strategy: THROW_TASK
  thread:
    thread-name: thread # 工作线程名称
    max-free-time: 180 # 普通线程池线程最大闲置时间，超时后会被线程池回收



# MVC配置
mvc:
  resource-path: / #资源映射路径
  webpage-path: / #网页映射路径

# IOC配置
ioc:
  scan-path: / #拓展程序扫描路径

# 日志配置
log:
  choose-class: default # 拓展程序的类选择，如果没有找到则使用默认程序

